server:
  port: 8181

spring:
  application:
    name: ai-service
  datasource:
    url: jdbc:postgresql://localhost:5532/devmatch
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    clean-disabled: false
  ai:
    openai:
      api-key: env_var
      base-url: https://api.together.xyz/v1
      chat:
        options:
          model: meta-llama/Llama-3.3-70B-Instruct-Turbo-Free
          temperature: 0.2
          max-tokens: 1024
        completions-path: /chat/completions
      embedding:
        options:
          model: meta-llama/Llama-3.3-70B-Instruct-Turbo-Free

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1.0

app:
  ai:
    embedding:
      expected-dim: 3072
  security:
    disabled: true
